---
Name: sstweaks
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css: 
    - 'resources/vendor/roseblade/silverstripe-tweaks/client/dist/cms-tweaks.css'
  help_links:
    'Developer docs': ''
  cms_background: '#114759'
  cms_border_color: '#114759'
  cms_color: '#fff'
  cms_hover_background: '#0f5970'
  cms_active_background: '#2cadd7'
  cms_active_color: '#fff'
  cms_drawer_background: '#1d7b99'
SilverStripe\Control\Email\Email:
  admin_email: noreply@website-notify.com
SilverStripe\CMS\Model\VirtualPage:
  extensions:
    - PurpleSpider\SSTweaks\CannotCreatePage
SilverStripe\ErrorPage\ErrorPage:
  extensions:
    - PurpleSpider\SSTweaks\CannotCreatePage
SilverStripe\Assets\File:
  extensions:
    - PurpleSpider\SSTweaks\AllowFileUploads
SilverStripe\Security\Member:
  extensions:
    - PurpleSpider\SSTweaks\MemberTidy
    - PurpleSpider\SSTweaks\MemberLog
Page:
  extensions:
    - PurpleSpider\SSTweaks\PageHideDependent
    - PurpleSpider\SSTweaks\PageHideExtraMeta
    - PurpleSpider\SSTweaks\PageSettingsHideSearch
PSWDSite\HomePage:
    extensions:
        - PurpleSpider\SSTweaks\BlockPageArchive
gorriecoe\DevBuildKey\DevBuildKey:
    run_in_background: true
SilverStripe\SiteConfig\SiteConfig:
  cms_logo: 'vendor/roseblade/silverstripe-tweaks/client/dist/images/silverstripe-logo-v4.png'
  extensions:
    - Roseblade\DataExtension\SiteConfigExtension
    - Burnbright\SocialLinks\SiteConfigSocialLinksExtension
